spring.application.name=event-driven-order-integration-framework

server.port=8085

# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.retries=3

# Kafka Consumer Config
spring.kafka.consumer.group-id=order-processing-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trusted model packages for JSON deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.qa.event_driven_order_integration_framework.model,com.qa.eventdrivenorderintegrationframework.model

# Kafka Topic Names
topics.order-events=order-events
topics.processed-orders=processed-orders
topics.order-dlq=order-dlq

# Downstream Payment Service
payment.service.base-url=http://localhost:9099